// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: nodepresentation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodePresentationFlags int32

const (
	NodePresentationFlags_NODE_PRESENTATION_TYPE_HELLO   NodePresentationFlags = 0
	NodePresentationFlags_NODE_PRESENTATION_TYPE_GOODBYE NodePresentationFlags = 1
	NodePresentationFlags_NODE_PRESENTATION_TYPE_REFRESH NodePresentationFlags = 2
)

// Enum value maps for NodePresentationFlags.
var (
	NodePresentationFlags_name = map[int32]string{
		0: "NODE_PRESENTATION_TYPE_HELLO",
		1: "NODE_PRESENTATION_TYPE_GOODBYE",
		2: "NODE_PRESENTATION_TYPE_REFRESH",
	}
	NodePresentationFlags_value = map[string]int32{
		"NODE_PRESENTATION_TYPE_HELLO":   0,
		"NODE_PRESENTATION_TYPE_GOODBYE": 1,
		"NODE_PRESENTATION_TYPE_REFRESH": 2,
	}
)

func (x NodePresentationFlags) Enum() *NodePresentationFlags {
	p := new(NodePresentationFlags)
	*p = x
	return p
}

func (x NodePresentationFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodePresentationFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_nodepresentation_proto_enumTypes[0].Descriptor()
}

func (NodePresentationFlags) Type() protoreflect.EnumType {
	return &file_nodepresentation_proto_enumTypes[0]
}

func (x NodePresentationFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodePresentationFlags.Descriptor instead.
func (NodePresentationFlags) EnumDescriptor() ([]byte, []int) {
	return file_nodepresentation_proto_rawDescGZIP(), []int{0}
}

type NodePresentation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,2,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	CompileTime     string                 `protobuf:"bytes,3,opt,name=compile_time,json=compileTime,proto3" json:"compile_time,omitempty"`
	LibVersion      string                 `protobuf:"bytes,4,opt,name=lib_version,json=libVersion,proto3" json:"lib_version,omitempty"`
	Type            NodePresentationFlags  `protobuf:"varint,5,opt,name=type,proto3,enum=espmeshmesh.NodePresentationFlags" json:"type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodePresentation) Reset() {
	*x = NodePresentation{}
	mi := &file_nodepresentation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePresentation) ProtoMessage() {}

func (x *NodePresentation) ProtoReflect() protoreflect.Message {
	mi := &file_nodepresentation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePresentation.ProtoReflect.Descriptor instead.
func (*NodePresentation) Descriptor() ([]byte, []int) {
	return file_nodepresentation_proto_rawDescGZIP(), []int{0}
}

func (x *NodePresentation) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodePresentation) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *NodePresentation) GetCompileTime() string {
	if x != nil {
		return x.CompileTime
	}
	return ""
}

func (x *NodePresentation) GetLibVersion() string {
	if x != nil {
		return x.LibVersion
	}
	return ""
}

func (x *NodePresentation) GetType() NodePresentationFlags {
	if x != nil {
		return x.Type
	}
	return NodePresentationFlags_NODE_PRESENTATION_TYPE_HELLO
}

var File_nodepresentation_proto protoreflect.FileDescriptor

const file_nodepresentation_proto_rawDesc = "" +
	"\n" +
	"\x16nodepresentation.proto\x12\vespmeshmesh\"\xd5\x01\n" +
	"\x10NodePresentation\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12)\n" +
	"\x10firmware_version\x18\x02 \x01(\tR\x0ffirmwareVersion\x12!\n" +
	"\fcompile_time\x18\x03 \x01(\tR\vcompileTime\x12\x1f\n" +
	"\vlib_version\x18\x04 \x01(\tR\n" +
	"libVersion\x126\n" +
	"\x04type\x18\x05 \x01(\x0e2\".espmeshmesh.NodePresentationFlagsR\x04type*\x81\x01\n" +
	"\x15NodePresentationFlags\x12 \n" +
	"\x1cNODE_PRESENTATION_TYPE_HELLO\x10\x00\x12\"\n" +
	"\x1eNODE_PRESENTATION_TYPE_GOODBYE\x10\x01\x12\"\n" +
	"\x1eNODE_PRESENTATION_TYPE_REFRESH\x10\x02B\x0fZ\r./meshmesh/pbb\x06proto3"

var (
	file_nodepresentation_proto_rawDescOnce sync.Once
	file_nodepresentation_proto_rawDescData []byte
)

func file_nodepresentation_proto_rawDescGZIP() []byte {
	file_nodepresentation_proto_rawDescOnce.Do(func() {
		file_nodepresentation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodepresentation_proto_rawDesc), len(file_nodepresentation_proto_rawDesc)))
	})
	return file_nodepresentation_proto_rawDescData
}

var file_nodepresentation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nodepresentation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nodepresentation_proto_goTypes = []any{
	(NodePresentationFlags)(0), // 0: espmeshmesh.NodePresentationFlags
	(*NodePresentation)(nil),   // 1: espmeshmesh.NodePresentation
}
var file_nodepresentation_proto_depIdxs = []int32{
	0, // 0: espmeshmesh.NodePresentation.type:type_name -> espmeshmesh.NodePresentationFlags
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nodepresentation_proto_init() }
func file_nodepresentation_proto_init() {
	if File_nodepresentation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodepresentation_proto_rawDesc), len(file_nodepresentation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodepresentation_proto_goTypes,
		DependencyIndexes: file_nodepresentation_proto_depIdxs,
		EnumInfos:         file_nodepresentation_proto_enumTypes,
		MessageInfos:      file_nodepresentation_proto_msgTypes,
	}.Build()
	File_nodepresentation_proto = out.File
	file_nodepresentation_proto_goTypes = nil
	file_nodepresentation_proto_depIdxs = nil
}
