// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: nodeinfo.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FriendlyName    string                 `protobuf:"bytes,1,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,2,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	MacAddress      string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Platform        string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Board           string                 `protobuf:"bytes,5,opt,name=board,proto3" json:"board,omitempty"`
	CompileTime     string                 `protobuf:"bytes,6,opt,name=compile_time,json=compileTime,proto3" json:"compile_time,omitempty"`
	LibVersion      string                 `protobuf:"bytes,7,opt,name=lib_version,json=libVersion,proto3" json:"lib_version,omitempty"`
	NodeType        int32                  `protobuf:"varint,8,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_nodeinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nodeinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_nodeinfo_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *NodeInfo) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *NodeInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NodeInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *NodeInfo) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *NodeInfo) GetCompileTime() string {
	if x != nil {
		return x.CompileTime
	}
	return ""
}

func (x *NodeInfo) GetLibVersion() string {
	if x != nil {
		return x.LibVersion
	}
	return ""
}

func (x *NodeInfo) GetNodeType() int32 {
	if x != nil {
		return x.NodeType
	}
	return 0
}

var File_nodeinfo_proto protoreflect.FileDescriptor

const file_nodeinfo_proto_rawDesc = "" +
	"\n" +
	"\x0enodeinfo.proto\x12\vespmeshmesh\"\x8e\x02\n" +
	"\bNodeInfo\x12#\n" +
	"\rfriendly_name\x18\x01 \x01(\tR\ffriendlyName\x12)\n" +
	"\x10firmware_version\x18\x02 \x01(\tR\x0ffirmwareVersion\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x14\n" +
	"\x05board\x18\x05 \x01(\tR\x05board\x12!\n" +
	"\fcompile_time\x18\x06 \x01(\tR\vcompileTime\x12\x1f\n" +
	"\vlib_version\x18\a \x01(\tR\n" +
	"libVersion\x12\x1b\n" +
	"\tnode_type\x18\b \x01(\x05R\bnodeTypeB\x0fZ\r./meshmesh/pbb\x06proto3"

var (
	file_nodeinfo_proto_rawDescOnce sync.Once
	file_nodeinfo_proto_rawDescData []byte
)

func file_nodeinfo_proto_rawDescGZIP() []byte {
	file_nodeinfo_proto_rawDescOnce.Do(func() {
		file_nodeinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeinfo_proto_rawDesc), len(file_nodeinfo_proto_rawDesc)))
	})
	return file_nodeinfo_proto_rawDescData
}

var file_nodeinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nodeinfo_proto_goTypes = []any{
	(*NodeInfo)(nil), // 0: espmeshmesh.NodeInfo
}
var file_nodeinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodeinfo_proto_init() }
func file_nodeinfo_proto_init() {
	if File_nodeinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeinfo_proto_rawDesc), len(file_nodeinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodeinfo_proto_goTypes,
		DependencyIndexes: file_nodeinfo_proto_depIdxs,
		MessageInfos:      file_nodeinfo_proto_msgTypes,
	}.Build()
	File_nodeinfo_proto = out.File
	file_nodeinfo_proto_goTypes = nil
	file_nodeinfo_proto_depIdxs = nil
}
