// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: nodepresentation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodePresentation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,2,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	CompileTime     string                 `protobuf:"bytes,3,opt,name=compile_time,json=compileTime,proto3" json:"compile_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodePresentation) Reset() {
	*x = NodePresentation{}
	mi := &file_nodepresentation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePresentation) ProtoMessage() {}

func (x *NodePresentation) ProtoReflect() protoreflect.Message {
	mi := &file_nodepresentation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePresentation.ProtoReflect.Descriptor instead.
func (*NodePresentation) Descriptor() ([]byte, []int) {
	return file_nodepresentation_proto_rawDescGZIP(), []int{0}
}

func (x *NodePresentation) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodePresentation) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *NodePresentation) GetCompileTime() string {
	if x != nil {
		return x.CompileTime
	}
	return ""
}

var File_nodepresentation_proto protoreflect.FileDescriptor

const file_nodepresentation_proto_rawDesc = "" +
	"\n" +
	"\x16nodepresentation.proto\x12\vespmeshmesh\"|\n" +
	"\x10NodePresentation\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12)\n" +
	"\x10firmware_version\x18\x02 \x01(\tR\x0ffirmwareVersion\x12!\n" +
	"\fcompile_time\x18\x03 \x01(\tR\vcompileTimeB\x0fZ\r./meshmesh/pbb\x06proto3"

var (
	file_nodepresentation_proto_rawDescOnce sync.Once
	file_nodepresentation_proto_rawDescData []byte
)

func file_nodepresentation_proto_rawDescGZIP() []byte {
	file_nodepresentation_proto_rawDescOnce.Do(func() {
		file_nodepresentation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodepresentation_proto_rawDesc), len(file_nodepresentation_proto_rawDesc)))
	})
	return file_nodepresentation_proto_rawDescData
}

var file_nodepresentation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nodepresentation_proto_goTypes = []any{
	(*NodePresentation)(nil), // 0: espmeshmesh.NodePresentation
}
var file_nodepresentation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodepresentation_proto_init() }
func file_nodepresentation_proto_init() {
	if File_nodepresentation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodepresentation_proto_rawDesc), len(file_nodepresentation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodepresentation_proto_goTypes,
		DependencyIndexes: file_nodepresentation_proto_depIdxs,
		MessageInfos:      file_nodepresentation_proto_msgTypes,
	}.Build()
	File_nodepresentation_proto = out.File
	file_nodepresentation_proto_goTypes = nil
	file_nodepresentation_proto_depIdxs = nil
}
