// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: pathrouting.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PathDirection int32

const (
	PathDirection_TO_COORDINATOR PathDirection = 0
	PathDirection_TO_NODE        PathDirection = 1
)

// Enum value maps for PathDirection.
var (
	PathDirection_name = map[int32]string{
		0: "TO_COORDINATOR",
		1: "TO_NODE",
	}
	PathDirection_value = map[string]int32{
		"TO_COORDINATOR": 0,
		"TO_NODE":        1,
	}
)

func (x PathDirection) Enum() *PathDirection {
	p := new(PathDirection)
	*p = x
	return p
}

func (x PathDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_pathrouting_proto_enumTypes[0].Descriptor()
}

func (PathDirection) Type() protoreflect.EnumType {
	return &file_pathrouting_proto_enumTypes[0]
}

func (x PathDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathDirection.Descriptor instead.
func (PathDirection) EnumDescriptor() ([]byte, []int) {
	return file_pathrouting_proto_rawDescGZIP(), []int{0}
}

type PathRouting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceAddress uint32                 `protobuf:"varint,1,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	TargetAddress uint32                 `protobuf:"varint,2,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	Repeaters     []uint32               `protobuf:"varint,3,rep,packed,name=repeaters,proto3" json:"repeaters,omitempty"`
	Rssi          []int32                `protobuf:"varint,4,rep,packed,name=rssi,proto3" json:"rssi,omitempty"`
	HopIndex      uint32                 `protobuf:"varint,5,opt,name=hop_index,json=hopIndex,proto3" json:"hop_index,omitempty"`
	Direction     PathDirection          `protobuf:"varint,6,opt,name=direction,proto3,enum=espmeshmesh.PathDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRouting) Reset() {
	*x = PathRouting{}
	mi := &file_pathrouting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRouting) ProtoMessage() {}

func (x *PathRouting) ProtoReflect() protoreflect.Message {
	mi := &file_pathrouting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRouting.ProtoReflect.Descriptor instead.
func (*PathRouting) Descriptor() ([]byte, []int) {
	return file_pathrouting_proto_rawDescGZIP(), []int{0}
}

func (x *PathRouting) GetSourceAddress() uint32 {
	if x != nil {
		return x.SourceAddress
	}
	return 0
}

func (x *PathRouting) GetTargetAddress() uint32 {
	if x != nil {
		return x.TargetAddress
	}
	return 0
}

func (x *PathRouting) GetRepeaters() []uint32 {
	if x != nil {
		return x.Repeaters
	}
	return nil
}

func (x *PathRouting) GetRssi() []int32 {
	if x != nil {
		return x.Rssi
	}
	return nil
}

func (x *PathRouting) GetHopIndex() uint32 {
	if x != nil {
		return x.HopIndex
	}
	return 0
}

func (x *PathRouting) GetDirection() PathDirection {
	if x != nil {
		return x.Direction
	}
	return PathDirection_TO_COORDINATOR
}

var File_pathrouting_proto protoreflect.FileDescriptor

const file_pathrouting_proto_rawDesc = "" +
	"\n" +
	"\x11pathrouting.proto\x12\vespmeshmesh\"\xe4\x01\n" +
	"\vPathRouting\x12%\n" +
	"\x0esource_address\x18\x01 \x01(\rR\rsourceAddress\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\rR\rtargetAddress\x12\x1c\n" +
	"\trepeaters\x18\x03 \x03(\rR\trepeaters\x12\x12\n" +
	"\x04rssi\x18\x04 \x03(\x05R\x04rssi\x12\x1b\n" +
	"\thop_index\x18\x05 \x01(\rR\bhopIndex\x128\n" +
	"\tdirection\x18\x06 \x01(\x0e2\x1a.espmeshmesh.PathDirectionR\tdirection*0\n" +
	"\rPathDirection\x12\x12\n" +
	"\x0eTO_COORDINATOR\x10\x00\x12\v\n" +
	"\aTO_NODE\x10\x01B\x0fZ\r./meshmesh/pbb\x06proto3"

var (
	file_pathrouting_proto_rawDescOnce sync.Once
	file_pathrouting_proto_rawDescData []byte
)

func file_pathrouting_proto_rawDescGZIP() []byte {
	file_pathrouting_proto_rawDescOnce.Do(func() {
		file_pathrouting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pathrouting_proto_rawDesc), len(file_pathrouting_proto_rawDesc)))
	})
	return file_pathrouting_proto_rawDescData
}

var file_pathrouting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pathrouting_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pathrouting_proto_goTypes = []any{
	(PathDirection)(0),  // 0: espmeshmesh.PathDirection
	(*PathRouting)(nil), // 1: espmeshmesh.PathRouting
}
var file_pathrouting_proto_depIdxs = []int32{
	0, // 0: espmeshmesh.PathRouting.direction:type_name -> espmeshmesh.PathDirection
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pathrouting_proto_init() }
func file_pathrouting_proto_init() {
	if File_pathrouting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pathrouting_proto_rawDesc), len(file_pathrouting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pathrouting_proto_goTypes,
		DependencyIndexes: file_pathrouting_proto_depIdxs,
		EnumInfos:         file_pathrouting_proto_enumTypes,
		MessageInfos:      file_pathrouting_proto_msgTypes,
	}.Build()
	File_pathrouting_proto = out.File
	file_pathrouting_proto_goTypes = nil
	file_pathrouting_proto_depIdxs = nil
}
