name: "espMeshMesh Server"
description: "The espMeshMesh Server"

version: "0.1.0"
slug: "espMeshMeshgo"

url: https://github.com/EspMeshMesh/meshmeshgo

arch:
  - aarch64
  - amd64
  - i386

#discovery:
#  - combadge

panel_icon: mdi:access-point-network
homeassistant: 2025.9.0

options:
  SerialPortName: ""
  SerialPortBaudRate: 460800
  WantHelp: true
  esp8266: false
  VerboseLevel: 0
  RestBindAddress: ":4000"
  BindAddress: "dynamic"
  BindPort: 6053
  BasePortOffset: 20000
  SizeOfPortsPool: 10000

schema:
  SerialPortName: device(subsystem=tty)
  SerialPortBaudRate: int?
  WantHelp: bool?
  esp8266: bool?
  VerboseLevel: int?
  TargetNode: int?
  DebugNodeAddr": int?
  RestBindAddress: str?
  RpcBindAddress: str?
  BindAddress: str?
  BindPort: int?
  BasePortOffset: int?
  SizeOfPortsPool: int?

ports:
  4040/tcp: 4040

init: false
startup: "services"
boot: "auto"

#host_network: true
#homeassistant_api: true
#$hassio_api: true
#audio: true
#usb: true
#auth_api: true

#uart: true
#devicetree: true

ingress: true
ingress_port: 8099

